title: Taro Katayama
logo: IMG_6862.png
description: I am an aspiring data scientist interested in water related issues, specifically water rights and water sustainability
email: tarokatayama1@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
