title: Taro Katayama (he/him)
logo: IMG_6862.png
theme: jekyll-theme-minimal
description: Aspiring data scientist interested in water related issues, specifically water rights and water sustainability. Tarokatayama1@gmail.com
show_downloads: true
  
