title: Taro Katayama
logo:
  image: IMG_6862.png
description: Portfolio for Taro Katayama (he/him). Showcases work that he has done. Tarokatayama1@gmail.com
email: "tarokatayama1@gmail.com"
show_downloads: true
theme: jekyll-theme-minimal
