title: Taro Katayama
logo: ![IMG_6862](https://github.com/tarokatayama/tarokatayama.github.io/assets/97321122/b22efe20-7844-4228-9a9c-e32e9d075efe)
description: Portfolio for Taro Katayama (he/him). Showcases work that he has done. Tarokatayama1@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
