title: Taro Katayama
logo: /Users/tarokatayama/Desktop/IMG_6862.jpg
description: Portfolio for Taro Katayama (he/him). Showcases work that he has done
show_downloads: true
theme: jekyll-theme-minimal
