title: Taro's Homepage
url: https://tarokatayama.github.io
theme: minimal-mistakes-jekyll

author:
  name: Taro Katayama (He/Him)
  logo: IMG_6862.png
  description: Aspiring data scientist interested in water related issues, specifically water rights and water sustainability
  location: Laramie, Wyoming
  email: tarokatayama1@gmail.com
  show_downloads: true
  
